# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de requerimientos y el código al contenedor
COPY  . .

# Instalar las dependencias

# Comando por defecto para ejecutar la aplicación con Uvicorn
CMD ["python3", "alto_1.py"]
