
FROM golang:1.23 as builder


WORKDIR /app


COPY . .


RUN go mod tidy


RUN GOOS=linux GOARCH=amd64 go build -o go_service .


RUN ls -l /app/go_service


FROM alpine:latest


RUN apk add --no-cache libc6-compat


WORKDIR /app


COPY --from=builder /app/go_service .


RUN chmod +x /app/go_service


EXPOSE 50051


CMD ["./go_service"]