# Usar una imagen base de Go para compilar el servicio
FROM golang:1.23 as builder

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código fuente al contenedor
COPY . .

# Descargar dependencias
RUN go mod tidy

# Compilar el servicio
RUN GOOS=linux GOARCH=amd64 go build -o go_service .

# Verificar que el binario ha sido creado
RUN ls -l /app/go_service

# Crear una imagen mínima para ejecutar el binario compilado
FROM alpine:latest

# Instalar dependencias mínimas
RUN apk add --no-cache libc6-compat

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el binario compilado desde la fase anterior
COPY --from=builder /app/go_service .

# Asegurarse de que el binario tenga permisos de ejecución
RUN chmod +x /app/go_service

# Exponer el puerto que utilizará el servicio
EXPOSE 50051

# Comando para ejecutar la aplicación
CMD ["./go_service"]