apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-atlser-go
spec:
  selector:
    matchLabels:
      app: grpc-atlser-go
  template:
    metadata:
      labels:
        app: grpc-atlser-go
    spec:
      containers:
      - name:  grpc-atlser-go
        image: luiscastillo2001/atl-server:1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.3"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: athletics-server #DNS
spec:
  selector:
    app: grpc-atlser-go
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
