apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-swimmingser-go
spec:
  selector:
    matchLabels:
      app: grpc-swimmingser-go
  template:
    metadata:
      labels:
        app: grpc-swimmingser-go
    spec:
      containers:
      - name: grpc-swimmingser-go
        image: luiscastillo2001/swimming-server:1.8
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: swimming-server #DNS
spec:
  selector:
    app: grpc-swimmingser-go
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-swimmingser-go-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-swimmingser-go
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
