
FROM golang:1.23 as builder

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código fuente al contenedor
COPY . .


RUN go mod tidy


RUN GOOS=linux GOARCH=amd64 go build -o go_service .


RUN ls -l /app/go_service


FROM alpine:latest


RUN apk add --no-cache libc6-compat


WORKDIR /app


COPY --from=builder /app/go_service .


RUN chmod +x /app/go_service


CMD ["./go_service"]